package it.polimi.ingsw.message;

public enum Data {
    BOOKSHELF,BOARD,ERROR,RANKING,PLAYERS,CONTENT,COMMON_GOAL_CARD,SELECTED_ITEMS,
    WHO_CHANGE,NEW_BOARD,NEW_BOOKSHELF,POINTS,TOKEN,PERSONAL_GOAL_CARD,VALUE_CLIENT,
}
